name: Enviar Relatório Webhook

on:
  schedule:
    - cron: '0 12 * * *'  # Executa todo dia às 12h UTC (ajuste conforme necessário)

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install requests

      - name: Executar o script
        run: python enviar_webhook.py
