name: Enviar Relatório Webhook

on:
  workflow_dispatch:  # Permite rodar manualmente
  schedule:
    - cron: '0 0 * * *'  # Executa todo dia à meia-noite UTC

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar dependências
        run: pip install requests

      - name: Executar o script
        run: python assets/js/enviar_webhook.py
